inputString = input("input string = ")
inputStringLength = len(inputString)
print("0 - 4 " + inputString[0:4])
print("last 4 " + inputString[-4: inputStringLength])
center = int(inputStringLength / 2)
print("center " + inputString[center])
print("3-8 " + inputString[3: 8])
